skillMetadata:
  sections:
    - name: MQTT-Settings
      fields:
        - name: mqttbroker
          type: text
          label: Insert the broker's IP
          value:
        - name: mqttport
          type: number
          label: Insert the broker's Port
          value: 1883
    - name: Tasmota FullTopicSyntax
      fields:
        - name: fulltopicsyntax
          type: select
          label: Choose Tasmota's FullTopicSyntax
          options: '%prefix%/%topic%/ (default)|default;%topic%/%prefix%/(HomeAssistant)|homeassistant'
          value: default
    - name: Capitalization
      fields:
        - name: capitalization
          type: checkbox
          label: Click if device topics start with capital letters
          value: "false"
